#!/bin/bash
# Network Optimizer Pro - Linux Quick Optimization
# Run with sudo for full functionality

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_banner() {
    echo "============================================================"
    echo "   NETWORK OPTIMIZER PRO - Linux Quick Optimization"
    echo "============================================================"
    echo ""
}

print_status() {
    echo -e "${BLUE}[*]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[+]${NC} $1"
}

print_error() {
    echo -e "${RED}[-]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_warning "Not running as root (sudo)"
        print_warning "Some optimizations will be skipped"
        echo ""
        read -p "Press Enter to continue..."
        return 1
    fi
    print_success "Running with root privileges"
    return 0
}

backup_config() {
    print_status "Creating backup of network configuration..."
    local backup_dir="$HOME/network_backup_$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$backup_dir"
    
    if [ -f /etc/sysctl.conf ]; then
        cp /etc/sysctl.conf "$backup_dir/"
    fi
    if [ -f /etc/resolv.conf ]; then
        cp /etc/resolv.conf "$backup_dir/"
    fi
    
    print_success "Backup created at: $backup_dir"
}

test_dns_servers() {
    print_status "Testing DNS servers for lowest latency..."
    echo ""
    
    declare -A dns_servers=(
        ["Cloudflare"]="1.1.1.1"
        ["Google"]="8.8.8.8"
        ["Quad9"]="9.9.9.9"
        ["OpenDNS"]="208.67.222.222"
        ["AdGuard"]="94.140.14.14"
    )
    
    local fastest_name=""
    local fastest_ip=""
    local fastest_time=9999
    
    for name in "${!dns_servers[@]}"; do
        local ip="${dns_servers[$name]}"
        local start=$(date +%s%N)
        
        if timeout 2 bash -c "echo >/dev/tcp/$ip/53" 2>/dev/null; then
            local end=$(date +%s%N)
            local duration=$(( (end - start) / 1000000 ))
            echo "    $name ($ip): ${duration}ms"
            
            if [ $duration -lt $fastest_time ]; then
                fastest_time=$duration
                fastest_name=$name
                fastest_ip=$ip
            fi
        else
            echo "    $name ($ip): TIMEOUT"
        fi
    done
    
    echo ""
    print_success "Fastest DNS: $fastest_name ($fastest_ip) - ${fastest_time}ms"
    echo "$fastest_ip"
}

set_dns() {
    local dns_ip=$1
    print_status "Setting DNS to $dns_ip..."
    
    # Backup existing resolv.conf
    if [ -f /etc/resolv.conf ]; then
        cp /etc/resolv.conf /etc/resolv.conf.backup
    fi
    
    # Write new DNS configuration
    cat > /etc/resolv.conf << EOF
# Generated by Network Optimizer Pro
nameserver $dns_ip
nameserver 1.0.0.1
options edns0 trust-ad
EOF
    
    # Make it immutable to prevent automatic changes
    chattr +i /etc/resolv.conf 2>/dev/null || true
    
    print_success "DNS configured"
}

optimize_sysctl() {
    print_status "Optimizing kernel network parameters..."
    
    # Backup existing sysctl.conf
    if [ -f /etc/sysctl.conf ]; then
        cp /etc/sysctl.conf /etc/sysctl.conf.backup
    fi
    
    # Apply optimizations
    cat >> /etc/sysctl.conf << 'EOF'

# Network Optimizer Pro - Gaming & Low Latency Optimizations
# Added on $(date)

# TCP Fast Open
net.ipv4.tcp_fastopen = 3

# Enable BBR congestion control
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# TCP optimization
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_low_latency = 1

# Increase network buffers
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.core.netdev_max_backlog = 5000

# Reduce TIME_WAIT
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1

# Optimize for low latency
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 8192
EOF

    # Apply the settings
    sysctl -p >/dev/null 2>&1
    
    print_success "Kernel parameters optimized"
}

flush_dns_cache() {
    print_status "Flushing DNS cache..."
    
    # Try different methods based on what's available
    if command -v systemd-resolve >/dev/null 2>&1; then
        systemd-resolve --flush-caches 2>/dev/null
    elif command -v resolvectl >/dev/null 2>&1; then
        resolvectl flush-caches 2>/dev/null
    elif [ -f /etc/init.d/nscd ]; then
        /etc/init.d/nscd restart >/dev/null 2>&1
    fi
    
    print_success "DNS cache flushed"
}

show_network_stats() {
    print_status "Current Network Statistics:"
    echo "------------------------------------------------------------"
    
    # Show active interfaces
    echo ""
    echo "Active Network Interfaces:"
    ip -br addr show | grep UP
    
    # Show routing table
    echo ""
    echo "Default Route:"
    ip route | grep default
    
    # Show DNS
    echo ""
    echo "Current DNS:"
    grep nameserver /etc/resolv.conf
    
    # Show TCP congestion control
    echo ""
    echo "TCP Congestion Control:"
    sysctl net.ipv4.tcp_congestion_control 2>/dev/null
    
    echo ""
}

test_latency() {
    local host=${1:-8.8.8.8}
    print_status "Testing latency to $host..."
    ping -c 10 "$host"
}

optimize_network_interface() {
    print_status "Optimizing network interface settings..."
    
    # Get the primary network interface
    local interface=$(ip route | grep default | awk '{print $5}' | head -n1)
    
    if [ -z "$interface" ]; then
        print_error "Could not find active network interface"
        return
    fi
    
    print_status "Optimizing interface: $interface"
    
    # Disable generic receive offload (can cause issues)
    ethtool -K "$interface" gro off 2>/dev/null || true
    
    # Set ring buffer sizes
    ethtool -G "$interface" rx 4096 tx 4096 2>/dev/null || true
    
    print_success "Interface $interface optimized"
}

run_full_optimization() {
    echo ""
    echo "============================================================"
    echo "  STARTING FULL NETWORK OPTIMIZATION"
    echo "============================================================"
    echo ""
    
    local is_root=0
    check_root && is_root=1
    
    if [ $is_root -eq 1 ]; then
        backup_config
        echo ""
    fi
    
    # Test and set DNS
    local fastest_dns=$(test_dns_servers)
    echo ""
    
    if [ $is_root -eq 1 ]; then
        set_dns "$fastest_dns"
        echo ""
        
        optimize_sysctl
        echo ""
        
        optimize_network_interface
        echo ""
    fi
    
    flush_dns_cache
    echo ""
    
    show_network_stats
    
    test_latency
    
    echo ""
    echo "============================================================"
    echo "  OPTIMIZATION COMPLETE!"
    echo "============================================================"
    echo ""
    print_success "Your network has been optimized for gaming and low latency"
    
    if [ $is_root -eq 1 ]; then
        print_warning "Backup created in: $HOME/network_backup_*"
        print_warning "Some changes require a reboot to take full effect"
    fi
    echo ""
}

show_menu() {
    while true; do
        echo ""
        echo "============================================================"
        echo "  NETWORK OPTIMIZER PRO - MENU"
        echo "============================================================"
        echo "1. Run Full Optimization"
        echo "2. Test & Set Fastest DNS"
        echo "3. Flush DNS Cache"
        echo "4. Show Network Statistics"
        echo "5. Test Latency (Ping)"
        echo "6. Optimize Kernel Parameters Only"
        echo "7. Exit"
        echo "============================================================"
        echo ""
        
        read -p "Select option (1-7): " choice
        
        case $choice in
            1)
                run_full_optimization
                ;;
            2)
                local fastest_dns=$(test_dns_servers)
                if [ "$EUID" -eq 0 ]; then
                    set_dns "$fastest_dns"
                else
                    print_warning "Run with sudo to apply DNS changes"
                fi
                ;;
            3)
                flush_dns_cache
                ;;
            4)
                show_network_stats
                ;;
            5)
                read -p "Enter host to ping (default: 8.8.8.8): " host
                host=${host:-8.8.8.8}
                test_latency "$host"
                ;;
            6)
                if [ "$EUID" -eq 0 ]; then
                    optimize_sysctl
                else
                    print_error "Must run with sudo to modify kernel parameters"
                fi
                ;;
            7)
                print_success "Thanks for using Network Optimizer Pro!"
                exit 0
                ;;
            *)
                print_error "Invalid option"
                ;;
        esac
    done
}

main() {
    print_banner
    
    if [ "$#" -gt 0 ]; then
        case "$1" in
            --optimize|-o)
                run_full_optimization
                ;;
            --dns)
                test_dns_servers
                ;;
            --stats)
                show_network_stats
                ;;
            *)
                echo "Usage: $0 [--optimize|--dns|--stats]"
                exit 1
                ;;
        esac
    else
        show_menu
    fi
}

main "$@"
